# Quantum DevOps CI Configuration
# Advanced configuration for quantum computing DevOps pipelines

# Hardware access and resource management
hardware_access:
  providers:
    ibmq:
      credentials_env: IBMQ_TOKEN
      max_monthly_shots: 1000000
      priority_queue: research
      cost_tracking: true
      
    aws_braket:
      credentials_env: AWS_BRAKET_CREDENTIALS
      devices:
        - name: Aria-1
          hourly_quota: 2
          max_circuit_depth: 20
          cost_per_shot: 0.00075
          
    google_quantum:
      credentials_env: GOOGLE_QUANTUM_KEY
      processors: [rainbow, weber]
      max_runtime_hours: 4

# Environment-based quota rules
quota_rules:
  development:
    branches: [develop, feature/*, fix/*]
    max_shots_per_run: 1000
    allowed_backends: [qasm_simulator, statevector_simulator]
    cost_limit_usd: 10.0
    auto_approve: true
    
  staging:
    branches: [staging, release/*]
    max_shots_per_run: 10000
    allowed_backends: [qasm_simulator, ibmq_qasm_simulator]
    cost_limit_usd: 100.0
    requires_approval: false
    
  production:
    branches: [main, production]
    max_shots_per_run: 100000
    allowed_backends: [all]
    cost_limit_usd: 1000.0
    requires_approval: true
    notification_channels: [slack, email]

# Quantum circuit linting configuration
circuit_linting:
  pulse_constraints:
    max_amplitude: 1.0
    min_pulse_duration: 16  # dt units
    phase_granularity: 0.01
    frequency_limits:
      - channel: d0
        min: -300e6
        max: 300e6
      - channel: d1
        min: -300e6
        max: 300e6

  gate_constraints:
    allowed_gates:
      - name: cx
        qubits: [[0,1], [1,2], [2,3], [3,4]]
      - name: rz
        qubits: all
      - name: sx
        qubits: all
    max_circuit_depth: 100
    max_two_qubit_gates: 50
    max_total_qubits: 20

  optimization:
    enable_gate_fusion: true
    enable_commutation_analysis: true
    enable_noise_adaptive_layout: true
    transpile_optimization_level: 3

# Noise simulation configuration
noise_simulation:
  default_noise_models:
    - name: ibmq_manhattan
      error_rates:
        single_qubit: 0.001
        two_qubit: 0.01
        readout: 0.02
    - name: custom_noise
      thermal_relaxation: true
      dephasing: true
      crosstalk: 0.005

  testing_thresholds:
    min_fidelity: 0.85
    max_error_rate: 0.15
    shots_for_validation: 8192

# Performance monitoring and benchmarking  
monitoring:
  performance_tracking:
    enable_circuit_profiling: true
    enable_cost_tracking: true
    enable_fidelity_monitoring: true
    
  benchmarks:
    - name: variational_algorithms
      circuits: [vqe, qaoa, ansatz_optimization]
      metrics: [depth, gate_count, estimated_fidelity]
      
    - name: quantum_machine_learning
      circuits: [qcnn, qgan, variational_classifier]
      metrics: [training_time, accuracy, resource_usage]

  alerts:
    performance_degradation: 20  # percent
    cost_threshold: 500  # USD
    error_rate_spike: 50  # percent increase

# Security and compliance
security:
  secrets_management:
    quantum_credentials_rotation: 30  # days
    hardware_token_encryption: true
    audit_logging: true
    
  compliance:
    data_retention: 90  # days
    export_control_compliance: true
    gdpr_compliance: true
    
  access_control:
    hardware_access_approval: true
    cost_approval_threshold: 100  # USD
    multi_factor_auth: true

# Testing framework configuration
testing:
  frameworks:
    pytest:
      quantum_fixtures: true
      noise_simulation: true
      parallel_execution: true
      coverage_threshold: 85
      
    quantum_specific:
      enable_fidelity_tests: true
      enable_noise_robustness_tests: true
      enable_hardware_compatibility_tests: true
      
  test_environments:
    local:
      simulators: [aer, qsim, pennylane]
      max_qubits: 30
      
    cloud:
      enable_hardware_tests: false
      max_monthly_budget: 500  # USD
      
    ci_cd:
      quick_tests_only: true
      max_execution_time: 300  # seconds
      parallel_workers: 4

# Resource optimization
optimization:
  cost_optimization:
    enable_intelligent_scheduling: true
    prefer_simulators: development
    batch_similar_experiments: true
    
  performance_optimization:
    circuit_compilation_caching: true
    result_caching: true
    parallel_circuit_execution: true
    
  resource_management:
    auto_cleanup_old_results: 30  # days
    compress_large_datasets: true
    enable_result_streaming: true

# Integration settings
integrations:
  ci_cd:
    github_actions: true
    gitlab_ci: true
    jenkins: true
    
  monitoring:
    datadog: false
    prometheus: false
    custom_webhooks: []
    
  notifications:
    slack:
      webhook_url_env: SLACK_WEBHOOK_URL
      channels: [quantum-ci, alerts]
    email:
      smtp_server_env: SMTP_SERVER
      recipients: [team@quantum-devops.org]

# Development and debugging
development:
  debugging:
    enable_circuit_visualization: true
    enable_state_inspection: true
    enable_performance_profiling: true
    
  local_development:
    auto_install_dependencies: true
    enable_hot_reload: true
    mock_hardware_responses: true
    
  documentation:
    auto_generate_api_docs: true
    include_circuit_examples: true
    generate_performance_reports: true