quantum_devops_ci:
  version: '1.0.0'
  framework: qiskit
  provider: ibmq

hardware_access:
  providers:
    - name: ibmq
      credentials_secret: IBMQ_TOKEN
      max_monthly_shots: 10_000_000
      priority_queue: research
      
    - name: aws_braket
      credentials_secret: AWS_CREDENTIALS
      devices:
        - name: Aria-1
          hourly_quota: 2
          max_circuit_depth: 20

testing:
  default_shots: 1000
  noise_simulation: true
  error_mitigation: false
  timeout_minutes: 30
  frameworks:
    - qiskit
    - cirq
    - pennylane
  
  backends:
    simulator:
      - qasm_simulator
      - statevector_simulator
    hardware:
      - least_busy
      - ibmq_qasm_simulator

quota_rules:
  - name: development
    branches: [develop, feature/*]
    max_shots_per_run: 1000
    allowed_backends: [simulator]
    
  - name: staging
    branches: [staging]
    max_shots_per_run: 10000
    allowed_backends: [simulator, ibmq_qasm_simulator]
    
  - name: production
    branches: [main]
    max_shots_per_run: 100000
    allowed_backends: [all]
    requires_approval: true

pulse_constraints:
  max_amplitude: 1.0
  min_pulse_duration: 16  # dt units
  phase_granularity: 0.01
  frequency_limits:
    - channel: d0
      min: -300e6
      max: 300e6
    - channel: d1
      min: -300e6
      max: 300e6

gate_constraints:
  allowed_gates:
    - name: cx
      qubits: [[0,1], [1,2], [2,3]]
    - name: rz
      qubits: all
  max_circuit_depth: 100
  max_two_qubit_gates: 50
  check_connectivity: true

cost_optimization:
  monthly_budget: 5000  # USD
  priority_weights:
    production: 0.5
    research: 0.3
    development: 0.2
  auto_scaling:
    enabled: true
    min_workers: 2
    max_workers: 16
    scale_up_threshold: 0.8
    scale_down_threshold: 0.3

monitoring:
  enabled: true
  metrics:
    - execution_time
    - fidelity
    - error_rate
    - cost_per_shot
    - queue_time
  dashboard_url: https://quantum-metrics.company.com
  alerts:
    cost_threshold: 4000  # 80% of budget
    error_rate_threshold: 0.05
    queue_time_threshold: 300  # seconds

security:
  encryption_at_rest: true
  encryption_in_transit: true
  access_logging: true
  secret_scanning: true
  allowed_ips: []  # Empty means all IPs allowed
  
deployment:
  strategy: blue_green
  validation:
    min_fidelity: 0.95
    max_error_rate: 0.05
    comparison_shots: 10000
  
  rollout:
    canary_percentage: 10
    increment: 10
    wait_between: 1h
    rollback_on_failure: true

internationalization:
  supported_languages: [en, es, fr, de, ja, zh]
  default_language: en
  timezone: UTC