"""
CITemplate: GitHub Actions YAML generator for quantum circuit testing pipelines.

Generates workflow files that can be dropped directly into .github/workflows/
"""

from __future__ import annotations
from typing import List, Optional


class CITemplate:
    """
    Generates GitHub Actions workflow YAML for quantum CI/CD pipelines.

    Args:
        repo_name: Repository name (used in workflow title)
        python_versions: Python versions to test against
        noise_levels: Noise levels for CI testing (passed as env vars)
        fidelity_threshold: Minimum fidelity threshold for test pass
        shots: Simulation shots per noise level
        on_push_branches: Branches to trigger on push
        enable_resource_estimation: Include resource estimation step
    """

    def __init__(
        self,
        repo_name: str = "quantum-project",
        python_versions: Optional[List[str]] = None,
        noise_levels: Optional[List[float]] = None,
        fidelity_threshold: float = 0.90,
        shots: int = 200,
        on_push_branches: Optional[List[str]] = None,
        enable_resource_estimation: bool = True,
    ):
        self.repo_name = repo_name
        self.python_versions = python_versions or ["3.10", "3.11", "3.12"]
        self.noise_levels = noise_levels or [0.0, 0.01, 0.05, 0.1]
        self.fidelity_threshold = fidelity_threshold
        self.shots = shots
        self.on_push_branches = on_push_branches or ["main", "develop"]
        self.enable_resource_estimation = enable_resource_estimation

    def generate(self) -> str:
        """Generate the complete GitHub Actions workflow YAML."""
        branches = "\n".join(f"          - {b}" for b in self.on_push_branches)
        py_matrix = str(self.python_versions).replace("'", '"')
        noise_str = ", ".join(str(n) for n in self.noise_levels)

        resource_step = ""
        if self.enable_resource_estimation:
            resource_step = """
      - name: Resource Estimation
        run: |
          python -c "
          from quantum_devops import ResourceEstimator
          from examples.circuits import EXAMPLE_CIRCUITS
          est = ResourceEstimator()
          for circuit in EXAMPLE_CIRCUITS:
              report = est.estimate(circuit)
              print(report.summary())
          "
"""

        return f"""\
# Quantum CI/CD Pipeline — generated by quantum-devops-ci CITemplate
# Drop this into .github/workflows/quantum-ci.yml

name: Quantum CI — {self.repo_name}

on:
  push:
    branches:
{branches}
  pull_request:
    branches:
{branches}

env:
  NOISE_LEVELS: "{noise_str}"
  FIDELITY_THRESHOLD: "{self.fidelity_threshold}"
  SHOTS: "{self.shots}"

jobs:
  noise-aware-tests:
    name: "Noise-Aware Circuit Tests (Python ${{{{ matrix.python-version }}}})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: {py_matrix}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{{{ matrix.python-version }}}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{{{ matrix.python-version }}}}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Validate circuits (lint)
        run: |
          python -m quantum_devops.cli validate circuits/
        continue-on-error: false

      - name: Run noise-aware tests
        run: |
          python -m pytest tests/ \\
            --noise-levels="$NOISE_LEVELS" \\
            --fidelity-threshold="$FIDELITY_THRESHOLD" \\
            --shots="$SHOTS" \\
            -v --tb=short
        env:
          QUANTUM_CI_MODE: "1"
{resource_step}
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quantum-test-results-py${{{{ matrix.python-version }}}}
          path: |
            test-results/
            *.json
          retention-days: 30

  resource-estimation:
    name: "Resource Estimation Report"
    runs-on: ubuntu-latest
    needs: noise-aware-tests
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - run: pip install -e ".[dev]"

      - name: Generate resource report
        run: |
          python -m quantum_devops.cli resources circuits/ --output resource-report.json

      - name: Check fault-tolerance budget
        run: |
          python -c "
          import json, sys
          with open('resource-report.json') as f:
              report = json.load(f)
          violations = [
              c for c in report['circuits']
              if c.get('t_gate_count', 0) > 1000
          ]
          if violations:
              print('T-gate budget exceeded:')
              for v in violations:
                  print(f'  {{v[\"name\"]}}: {{v[\"t_gate_count\"]}} T-gates')
              sys.exit(1)
          print('All circuits within T-gate budget.')
          "

      - name: Post resource summary
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('resource-report.json', 'utf8'));
            const body = '## Quantum Resource Estimation\\n\\n' +
              report.circuits.map(c =>
                `- **${{c.name}}**: ${{c.qubit_count}} qubits, depth ${{c.depth}}, ` +
                `${{c.gate_count}} gates, ${{c.t_gate_count}} T-gates`
              ).join('\\n');
            github.rest.issues.createComment({{
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            }});
"""

    def save(self, path: str = ".github/workflows/quantum-ci.yml") -> str:
        """Write workflow YAML to file. Returns the path written."""
        import os
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(self.generate())
        return path

    @classmethod
    def minimal(cls, repo_name: str = "quantum-project") -> str:
        """Generate a minimal workflow for quick onboarding."""
        return f"""\
# Minimal Quantum CI — generated by quantum-devops-ci
name: Quantum CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {{python-version: "3.12"}}
      - run: pip install quantum-devops-ci
      - run: python -m pytest tests/ -v
"""
